runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: nn.app

- url: /
  static_files: signin.html
  upload: signin.html


- url: /handlers.*
  script: signin.app

libraries:
  - name: webapp2
    version: latest
